//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANK_MANGMENT_SYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class userAccount
    {
        public decimal Account_No { get; set; }
        public string Name { get; set; }
        public string DOB { get; set; }
        public string PhoneNo { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public byte[] Picture { get; set; }
        public string Gender { get; set; }
        public string martial_status_ { get; set; }
        public string Mother_Name { get; set; }
        public string Father_Name { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string Date { get; set; }
    }
}
